openapi: 3.0.0
info:
  title: Login User API
  version: 1.0.0
paths:
  /login:
    post:
      summary: Login a user
      description: Authenticates a user and returns a JWT token.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Success to Login user
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  id:
                    type: integer
                  role:
                    type: string
                  access_tokern:
                    type: string
                  message:
                    type: string
        403:
          description: User not found or Invalid password
        500:
          description: Failed to Login User
